### ISSUE TITLE
OPEN_ORDER_LOTSIZE_OUT_OF_RANGE and OPEN_ORDER_PRICE_ZERO for usa500

### ISSUE THREAD

**Issue by mpele** [darwinex/dwxconnect#10]
I am using python for communication with DWX Server and I got strange errors when I want to work with usa500 symbol. I got error OPEN_ORDER_LOTSIZE_OUT_OF_RANGE , but when i disable this check in code i got error OPEN_ORDER_PRICE_ZERO. It looks like that function MarketInfo doesn't work as expectet for this symbol. 
Also I have noticed that for symbol ger40 I got error OPEN_ORDER_PRICE_ZERO . 

By the way, there is typo error in lines

https://github.com/darwinex/dwxconnect/blob/26a4b38f2aa4237e9e20b506289fd61edfb6c613/mql/DWX_Server_MT4.mq4#L273
https://github.com/darwinex/dwxconnect/blob/26a4b38f2aa4237e9e20b506289fd61edfb6c613/mql/DWX_Server_MT4.mq4#L324

it should be `Lot size out of range (min: %f, max: %f): %f ` instead `Lot size out of range (min: %f, max: %s): %f`

**Comment by elvinex** [comment]
Hi,

Thank you for spotting the typo. It is corrected now. 

Regarding the error, we can only support Darwinex and not other brokers. On a Darwinex demo accounts it seems to work as expected. 
Opening a 0.1 lots SPX500 position was successful. And when I changed the lot sizes to 0.01, it correctly produced the out of range error:

> ERROR | OPEN_ORDER_LOTSIZE_OUT_OF_RANGE | Lot size out of range (min: 0.100000, max: 1000.000000): 0.010000

**Comment by mpele** [comment]
Thank you for great tool that you provided to us !!!
