### ISSUE TITLE
Passing market depth data and spread to the client

### ISSUE THREAD

**Issue by Boscop** [darwinex/dwxconnect#15]
How would the code need to be extended in order to pass market depth / order book data to the client?
Which MQL functions should be called to fetch this data from MT?

And which MQL functions should be called to get the spread for a symbol?

**Comment by elvinex** [comment]
Hi,
Regarding the spread, I would not add a new function for that. If you are subscribed to a symbol, you can just use "ask minus bid" on the python side to get the spread. 

Market depth would only work on MT5, not MT4. DWX Connect does not offer this function yet, so you would have to add it yourself. 

Here is a great [video from Martyn](https://www.youtube.com/watch?v=lsIfKVDUGJc) explaining how to get market depth data:

An here is a link to the mql [documentation](https://www.mql5.com/en/docs/marketinformation/marketbookadd).
