### ISSUE TITLE
Backtesting with commisions / execution costs, which settings for MT StrategyTester?

### ISSUE THREAD

**Issue by Boscop** [darwinex/dwxconnect#16]
I want to backtest my EA in MT5 with real world conditions, by following these articles:
[IMPORTING HIGH QUALITY TICK DATA TO METATRADER 5](https://www.mql5.com/en/blogs/post/746240)
[CONFIGURING TRADING FEES IN THE MT5 STRATEGY TESTER WHEN BACKTESTING (CUSTOM SYMBOLS)
](https://www.mql5.com/en/blogs/post/746300)

https://help.darwinex.com/execution-costs
> In the case of both [Forex](https://www.darwinex.com/spreads/forex) and [commodities](https://www.darwinex.com/spreads/commodities), the gross commission always equals 0.005% of the nominal value of the base currency.
For instance, should you want to buy 1 lot on the EURUSD, that is 100.000 €, the total round-trip cost would be 5 €.

https://help.darwinex.com/calculate-the-pl-and-the-cost-of-a-forex-trade
> For currency pairs we charge 0.0025% of nominal value traded or a competitive 0.005% round trip.
In MT4, the entire round trip commission gets charged at the opening of the trade and no additional commission is charged afterwards.
However, in MT5 the commission is charged "per-side", half at the opening, half at the exit of the trade.

![image](https://user-images.githubusercontent.com/535593/167271529-02e2235b-9809-4d0f-9069-20ce21d26ef2.png)

I want to enter the execution costs / commisions, which values should I enter?

Charge: `Instant by deal volume` or `Instant by deal value`?
Entry: In/out deals?
From: ?
To: ?
Commission: ?
Minimal: ?
Maximal: ?
Mode: ?
Type: `per trade` or `per volume`?

![image](https://user-images.githubusercontent.com/535593/167271653-bf35cb68-7dab-425f-8608-2268a15a0b39.png)

![image](https://user-images.githubusercontent.com/535593/167271740-6c24e03a-f036-4f49-a0f2-a02f48ee637e.png)

![image](https://user-images.githubusercontent.com/535593/167271769-3fcd76f4-39d3-4b49-ae70-72d01e5bb904.png)

![image](https://user-images.githubusercontent.com/535593/167271780-03ad4a9d-6f91-444c-94d4-8f4892e8bf31.png)

---

On that dialog, there's an Import button. It would be nice if the Darwinex Team could add a file to this repo that can be imported, that contains the right settings for Darwinex's execution costs.

---

Btw, how high is the quality of the tick data that comes from Darwinex (when I don't import external tick data)?

**Comment by elvinex** [comment]
Hi,
This section is for issues with DWX connect. I am maintaining this repo, but I am not an employee of Darwinex. 
Regarding the MT5 settings, I think it would be best to ask in the mql5 forum. 

About the tick data quality it could be worth writing to the Darwinex support. Not sure, who has this information.

With regards to commissions, I wouldn't bother too much about getting the exact same as in live trading. There are so many other factors influencing backtest (slippage etc.) that differences in commission are negligible. I would just choose an upper estimate.
