### ISSUE TITLE
Zero Max Lot Size?

### ISSUE THREAD

**Issue by sorul** [darwinex/dwxconnect#22]
I have gotten the following error more than once. What is the point of the maximum lot size being 0.000? Why does this happen?

`('ERROR', '|', 'OPEN_ORDER_LOTSIZE_OUT_OF_RANGE', '|', 'Lot size out of range (min: 0.000000, max: 0.000000): 0.010000')`

Thank you.

**Comment by elvinex** [comment]
Hi,
The [mql code](https://github.com/darwinex/dwxconnect/blob/main/mql/DWX_Server_MT4.mq4) returns this error when the lot size is larger than `MarketInfo(symbol, MODE_MAXLOT)`. 

It seems that `MODE_MAXLOT` returned zero. My first guess would be that the symbol you are trying to trade is not tradable or does not exist (maybe different suffix). Or maybe it is an MT4 bug.
