### ISSUE TITLE
It places several orders.

### ISSUE THREAD

**Issue by krhismord** [darwinex/dwxconnect#27]
Sometimes when open_order() gets triggered it places several orders at the same time. It also happens in the example.

**Comment by SaraStemTrading** [comment]
Is there any solution for this? I have the same problem. Thank you so much.

**Comment by elvinex** [comment]
Hi,
sorry for the late reply. Could you add more info? I assume it is the python version, right? In combination with MT4 or MT5? 
I will try to replicate the issue. If you can replicate it, could you copy the log? 
Thanks!

**Comment by krhismord** [comment]
You should do the same with mt5 as well. It opens several positions when it
shouldn't. It is not as recurrent as the MT4 one, but it would be nice if
you lock the threads and make it check the ids.

**Comment by elvinex** [comment]
Thanks for the info. I updated all code (python, java, dotnet, MT4, MT5). If it happens with the new code, please let me know.
