### ISSUE TITLE
Latency performance of dwxconnect vs dwz-zeromq-connector

### ISSUE THREAD

**Issue by spliffli** [darwinex/dwxconnect#30]
Hi there,

I am planning on implementing a low-latency strategy where every millisecond counts. What I'd like to know is, whether dwxconnect or the old archived dwx-zeromq-connector has lower latency?  My first instinct is that zeromq would be faster since it's literally designed as a low-latency protocol. If I'm correct, then the file-based system of dwxconnect would be slower. Am I right in this assumption? Specifically I'm interested in trade execution speed/latency. Price feed latency is also important but not as important.

I suppose the best thing to do would be test them side-by-side. I'll probably do this when I have the time, but would love to hear the opinion of the creators from Darwinex.

Thanks

**Comment by spliffli** [comment]
Also, is changing the millisecond timer parameter in the Metatrader EA settings to 1ms a good or bad idea?

**Comment by elvinex** [comment]
Hi,
You can reduce the timers on both sides to the lowest possible, which depends on your CPU and read/write speed. 

I would also assume that zeromq is faster, but when I tested it some time ago, it seemed quite similar. 

Overall, if you really need extremely low latency, both are probably not the optimal choice. One could even argue MT4 alone is already too slow. But it depends on your exact requirements.

**Comment by spliffli** [comment]
> Hi, You can reduce the timers on both sides to the lowest possible, which depends on your CPU and read/write speed.
> 
> I would also assume that zeromq is faster, but when I tested it some time ago, it seemed quite similar.
> 
> Overall, if you really need extremely low latency, both are probably not the optimal choice. One could even argue MT4 alone is already too slow. But it depends on your exact requirements.

How would you measure or calculate the optimal millisecond timer value based on the CPU read/write speed?

The use-case for this is news trading i.e. Nonfarm Payrolls, GDP, CPI, PPI, Retail Sales, etc. using a low-latency news-feed then enter trades if the actual-forecast deviation is bullish or bearish (I made an analysis program in python which measures the correlation of the deviations to the price for each of these events and the lot size is calculated based on the correlation score, since a higher score should mean a higher probability of winning.

Right now I'm using [this](https://www.youtube.com/watch?v=ZevwBfZjp6g) program currently for doing that and it works by setting triggers for different deviations and then it automatically clicks on a pre-defined point on the screen where the buy and sell buttons are on metatrader.

This seems to work well even though I know that the windows API call to move the mouse and click takes about 50ms if I remember correctly (maybe more more less, it was a long time ago that I measured that). So I think the strategy should still work using either dwxconnect or the zmq connector.

You're still right however that mt4 isn't the best option for low-latency trading, and for that it's better to use FIX API but to open a FIX account there's usually a very high minimum deposit and my account isn't big enough for that yet.


So far I've only tested this strategy on a demo account but it's won every trade. The first trade with real money will be this friday so hopefully it will perform as well on a live account.

If you're interested in this strategy I made a [website](https://news-trading-system.netlify.app/weekly-schedules/week-15-schedule/) which has the recommended triggers generated by my python program to use with the haawks news trader program.

**Comment by spliffli** [comment]
The main advantage of using dwx-connect would be having the ability to trade multiple mt4 accounts with different lot sizes based on the trigger, as well as having more triggers than what's possible with the haawks program. It can also have a built-in timeout which aborts the trade if the news isn't received within 10 or 15 seconds (This can happen and it's best not to trade when it does). Right now I'm using an automatic mouse clicker which can  be scheduled to automatically click the button to de-activate trading)

**Comment by spliffli** [comment]
If you've stumbled upon this thread and you've never heard of this strategy, then I recommend looking into it. It's one of the few strategies which isn't based on technical analysis but rather external fundamental market forces that are quantifiable meaning it's possible to estimate the probability of each trade before making it using the correlation score (and in the future it will also account for how often whipsaw happens for each event and reduce the lots when that's higher).

However it's important to note that the low-latency news-feed [(haawks)](https://www.haawks.com/) costs €2k/month normally which is quite expensive and only worth it if your account is big enough to make more than that. They do offer free trials and discounts though.

**Comment by elvinex** [comment]
Ok, thanks for the info about the use case. 
But I don't know how to determine the optimum millisecond timer. 

Also, I would definitely recommend using a live account even if it is just with 0.01 lots. On a demo account there is no slippage. One a live account you can sometimes be filled 50 pips off the chart right after news.

**Comment by spliffli** [comment]
I think slippage shouldn't be too much or a problem with the broker I'm using (fpmarkets) because it was one of the best low-slippage & low-spread broker during news events which was measured in [this](https://offbeatforex.com/forex-brokers-for-trading-news/) article. 

So, I think 50 pip slippage is quite unlikely. It would be more likely for that to happen with a market-maker style broker who makes money from the spread and by being the counterparty to your trades i.e. winning when you lose. 

For ECN or STP brokers like fpmarkets the orders will just be filled at whatever the best price is in the orderbook and the average spreads for news events are only slightly more than when there's no news but it's not a big enough issue to stop the strategy from working. Slippage is normal for this type of trading but the price generally moves within the first second and then continues to move further after that. 

I'll just try out different settings for the millisecond timer and then test to see whatever works.

Also, today was the first actual trade on the live account for the Canada GDP release and it won but it only made 1.3 pips which was about €8. However, the entry seemed to be similar to the demo i.e. not that much slippage. It didn't make that much just because the price didn't move that much (the deviation was -0.1 which has a lower correlation score (79% I think) so the lot size was also smaller than if it had been a bigger deviation. If it had been +-0.2 then it would have used 6.1 lots and because the correlation is higher, the price probably would have moved more.

I'm sure there will be trades in the future where it catches more pips than that and then it'll make some real money. I don't expect it to never lose but I'm convinced that mathematically/statistically it has an edge i.e. a good probability of winning. That's all good theoretically but seeing how it will actually play out in reality will be interesting.

**Comment by spliffli** [comment]
[Here](https://www.youtube.com/watch?v=4oVssGjpPIQ) is a video of the trade. The next scheduled trade is NFP on the 5th of May and then the week after that there are 3 events

**Comment by spliffli** [comment]
It actually did move further into profit than the close price, but I had it set up with a trailing stoploss of 5 pips which closed the trade.

Anyway, to bring the topic back to dwxconnect, I think it would be interesting to be able to have multiple mt4 accounts to do things like A/B tests for different configurations e.g. using a slightly different calculation for the correlation or trying out different brokers and measuring execution time, slippage & spreads to find the best trading conditions.

I'm leaning kind of towards the zeromq connector instead of dwxconnect or maybe I'll try both options and benchmark/measure their latency then choose whichever is faster.

**Comment by spliffli** [comment]
Another thing to consider is that I want to connect to metatrader using the rust language. I'll make a program which connects to the haawks news-feed api, then once the news figure is received, calculates the deviation & checks predefined triggers just like the haawks program so it can open trades in metatrader based on the news deviation. 

Would dwxconnect or the zmq connector be better suited for that? Rust has performance just as fast as C/C++ so I think it would be well suited for the job. It also has good multithreading/concurrency which would probably be useful in designing such a system

**Comment by elvinex** [comment]
Thanks for the info. I don't think the blog post you mentioned measured the slippage. They just estimated it from the spread widening. But slippage is what is added on top. Splitting the lot size between multiple brokers makes sense. It will be interesting to see how it works live, especially in fast events. 

I can't really say which is better. The DWX zeromq repo is no longer maintained. So if there are problems, you have to find a way around them. You could also code your own Zeromq connection for any programming language (well the same is true for the file-based dwxconnect).

**Comment by elvinex** [comment]
@spliffli How are your tests going? I noticed you stopped publishing the results. 
Can we close this issue?
