### ISSUE TITLE
Getting Error everytime when order is placed. 

### ISSUE THREAD

**Issue by vivek-ram** [darwinex/dwxconnect#32]
on_order_event. open_orders: 1 open orders
ERROR | WRONG_FORMAT_COMMAND | Wrong format for command: MODIFY_ORDER|172088992,0.01,0,1838.02,0,0
ERROR | WRONG_FORMAT_COMMAND | Wrong format for command: MODIFY_ORDER|172088992,0.01,0,1838.02,0,0
ERROR | WRONG_FORMAT_COMMAND | Wrong format for command: MODIFY_ORDER|172088992,0.01,0,1838.02,0,0
ERROR | WRONG_FORMAT_COMMAND | Wrong format for command: MODIFY_ORDER|172088992,0.01,0,1838.02,0,0

**Comment by vivek-ram** [comment]
it happens in MT4. when i tried MT5 it got fixed.

**Comment by elvinex** [comment]
Hi,
In the last update we added a command ID so that a full command message looks like this:
command_id|command|content
In your example it only has one separator "|" and is missing the command ID, so my guess would be that the python code was not updated at the same time as MT4/5.
