### ISSUE TITLE
Error WRONG_FORMAT_START_IDENTIFIER

### ISSUE THREAD

**Issue by hoanhax** [darwinex/dwxconnect#35]
Hi, 

Thanks for the great project. I have used some connectors before (`Metatrader 5`, `dwx-zeromq-connector`), but now I have used `dwxconnect` for my project, because easy to use and removes zeromq dependency. 
When start using, I also worried about latency when using file to communicate between python and mql, but now I don't see any difference.
Recently sometimes I got the error :
 `WRONG_FORMAT_START_IDENTIFIER | Start identifier not found for command: `
I have checked code on file `DCWX_Server_MT4.mq4` it seems this error was logged by following code: 
`
 if (StringSubstr(text, 0, 2) != startIdentifier) {
         SendError("WRONG_FORMAT_START_IDENTIFIER", "Start identifier not found for command: " + text);
         return;
}
`

I have set `MILISECOND_TIMERS=5` in DWX_Server_MT4 expert.

**Comment by elvinex** [comment]
Hi,
If there was no text after `not found for command:`, then it seems the file was empty. 
I think in theory the mql side should not be allowed to open the file while it is in write process from python. But maybe it does sometimes anyway. Hopefully the command still goes through the next time it reads it.

**Comment by hoanhax** [comment]
thanks for your reply. 
Yes, it can still read data next time.
