### ISSUE TITLE
Expert Advisor insta closed

### ISSUE THREAD

**Issue by Sankyuubigan** [darwinex/dwxconnect#37]
why when you install an Expert Advisor on a chart, after 5 seconds it turns itself off, closes and disappears from the chart ?

**Comment by Sankyuubigan** [comment]
![image](https://github.com/darwinex/dwxconnect/assets/16042256/1d474e08-ecfc-4cb3-8787-81d7d4ab4d39)
MT4 closes the EA itself after a couple of seconds

**Comment by Sankyuubigan** [comment]
I didn't even connect to MT4 with the code. I'm just trying to configure the server, I just installed MT4 and I'm trying to run it on the chart but it fails after 10 tries.

**Comment by piotryordanov** [comment]
Maybe you are using the wrong expert code.
There is a version for MT5 and one for MT4

**Comment by Sankyuubigan** [comment]
> Maybe you are using the wrong expert code. There is a version for MT5 and one for MT4

I used the correct code. the same code worked on another computer. it turned out to be a matter of CPU and RAM utilization. as soon as I freed up the resources on the same machine, everything worked.
