### ISSUE TITLE
datetime.utcnow being deprecated

### ISSUE THREAD

**Issue by stuald** [darwinex/dwxconnect#43]
Hi guys,   through the code - this utcnow is referenced.  But its going away.
Is it possible to provide the string code to replace with in the client example and api and mql if required?

thanks

**Comment by elvinex** [comment]
Hi,
Thanks for bringing this up. I wasn't aware of it yet. I replaced all occurences with `datetime.now(timezone.utc)`. 
If you modify your own code, be sure to import timezone: `from datetime import timezone`
You could also just use `datetime.now()` if you don't care about the time zone.
